const data = {
    tc_normal:
`Countries Covered: 

Australia
China
Hong Kong
Japan
Malaysia
New Zealand
Philippines
Singapore
South Korea

Terms to be incorporated for all regions:  

1. SCOPE OF SERVICES.  First Advantage Limited (“First Advantage”) agrees to provide, pre-employment and employment screening services to Customer/Client (“You”) as detailed in accordance with the terms and conditions herein. By clicking the "ACCEPT" Button, You are consenting to be bound by this User Agreement.

2. Fees and Payment.  All amounts due by You, inclusive of service charges and applicable taxes, hereunder shall be paid in the currency selected via credit card or wire transfer to an account designated by First Advantage. The amounts due by You when settled are non-refundable. Wallet credits will be provided, which will be available for usage for succeeding transactions. Order cancellations post payments will be subject to wallet credits.  
First Advantage has an automated order assessment methodology that supports intelligent comparison of check orders paid versus actual checks required to be conducted based on candidate declared details. This methodology determines final amounts to be charged to You. As additional checks are detected, request for secondary payment will be secured from You to complete the transaction.

3. DISCLAIMER OF WARRANTIES.  First Advantage makes no and disclaim all warranties, conditions and representations with respect to the Services provided pursuant to this User Agreement, whether such warranties, conditions and representations are express or implied in fact or by operation of law, contained in or derived from this User Agreement, any other documents referenced in this User Agreement, or any other materials or communications whether oral or written, including without limitation, implied warranties or conditions of satisfactory quality, merchantability and fitness for a particular purpose and implied warranties arising from the course of dealing or a course of performance with respect to the accuracy, validity, or completeness of any Service.  You acknowledge and agree that First Advantage exercises no control over, and accepts no responsibility for your compliance with any law or regulation.

4. Applicable Privacy Laws.  You will comply with all "Applicable Privacy Laws", made available online at <br> <a style="color:blue !important;cursor:pointer" href="#legals" >“Legal Compliance”</a>. Any changes when any made to this section, will be posted at the above link. It is your responsibility to ensure that you understand and comply with all Applicable Privacy Laws, so you should periodically check this section for any changes.

5. INDEMNIFICATION.  You shall indemnify, defend and hold harmless First Advantage from and against any claim, suit, proceeding, damages, costs, expenses (including, without limitation, reasonable attorneys’ fees and court costs) brought by a third party against or suffered First Advantage arising from your violation of law, negligence or failure to comply with the terms and conditions of this User Agreement.

6. LIMITATION OF LIABILITY. First Advantage shall not be liable for any indirect, incidental, contingent, consequential, punitive, exemplary, special or similar damages, including but not limited to, loss of profits or loss of data, whether incurred as a result of negligence or otherwise.  First Advantage’s aggregate liability damages arising out of or in connection with this User Agreement, including as a result of any negligence on the part of First Advantage, shall not exceed three times the amount paid by You to First Advantage for the particular service giving rise to such damages. The limitations of the liability pursuant to this section applies only to the extent permitted by law.

7. Your Obligations.  You agree, and must ensure any organisation to which You provide any information provided to You by First Advantage agree that:

  a. You will only use the reports and information First Advantage provides for the purposes of pre-employment and employment screening or otherwise in accordance with the consent given to You by the relevant individual;

  b. You will take proper and reasonable steps to keep the information First Advantage supplies to You confidential and secure, and will not disclose it without the relevant individual’s consent except as otherwise permitted or required by law;

  c. First Advantage may modify the scope of Service at any time upon reasonable notice to You unless prior notice cannot be provided due to First Advantage’s obligations to comply with law, regulation and/or data provider requirements.  Notwithstanding anything to the contrary in this User Agreement, if First Advantage modifies the scope of the Service, You agree to comply with all such additional requirements and any additional fees or costs for such compliance which may be passed through to You.

  d. You warrant that the fax, email or mailing address You provide to First Advantage for correspondence is suitable for maintaining the confidentiality of the information First Advantage sends to You and You will notify First Advantage promptly if any need arises for You to change it; and

  e. First Advantage does not transfer any right, title or interest in any intellectual property rights in its business processes or in the Service that it is providing to You under this User Agreement.

8. Confidentiality.  The term “Confidential Information” means this User Agreement and all data, trade secrets, business and personal information and other information of any kind whatsoever that First Advantage discloses to You. You must not disclose Confidential Information provided by First Advantage to any third party other than on a “need to know” basis and then only to: (i) Your employees subject to a written confidentiality agreement and (iii) as required by law or as otherwise expressly permitted by this User Agreement.  You must not use or disclose Confidential Information of Discloser for any purpose other than to carry out this User Agreement. The obligations of confidentiality in this Section shall not apply to any information that: (i) You rightfully have in your possession when disclosed to it, free of obligation to First Advantage to maintain its confidentiality; (ii) You independently develop without access to First Advantage’s Confidential Information; (iii) is or becomes known to the public other than by breach of this Section by You; or (iv) is rightfully received by You from a third party without the obligation of confidentiality.

9. Termination: First Advantage will immediately terminate your right to receive any Service under this User Agreement if You fail to comply with the terms and conditions of this User Agreement, or You fail to comply with any law applicable to the Service provided to You pursuant to this User Agreement.

10. Miscellaneous: This User Agreement, constitute the final and entire agreement between the parties with respect to the Service. There are no representations, warranties, or agreements among the parties with respect to the Services contained herein, which are not fully expressed in this Agreement.  This User Agreement is governed by the laws of the Country where the Service is being provided and each party submits to the exclusive jurisdiction in and of the courts of  such countries and the courts which may hear appeals from those. If any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions shall be unaffected. A waiver by either party of any term or condition of this User Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. First Advantage may assign its rights under this User Agreement without condition. This User Agreement will be binding upon and inure to the benefit of the parties, their successors and permitted assigns. A listing of First Advantage’s Affiliates is set forth at: <a href="https://www.fadv.com/Portals/0/Downloads/legal/First_Advantage-Affiliate_Listing_10142016.pdf" target="_blank" >https://www.fadv.com/Portals/0/Downloads/legal/First_Advantage-Affiliate_Listing_10142016.pdf</a> .

<b id="legals">“Legal Compliance”</b>

A.   Australia

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Privacy Act 1988 (Cth), the Australian Privacy Principles, and State and Territory privacy laws, as amended from time to time; and the term "personal information" has the meaning designated by the Privacy Act 1988 (Cth).

  b. You agree that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledges and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertakes to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You has done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

B.   China

  In this User Agreement, “Applicable Laws” shall refer to country laws, directives, rules, regulations, executive orders, regulatory guidance, regulatory requirements and any form of secondary legislation, resolution, policy guideline, concession or case law from time to time that apply to either party and its affiliates or the services, including (i) data protection, privacy or similar laws and regulations anywhere in the world applicable to persons in possession of personal data or to the processing of personal data, and (ii) employment laws.  You agree that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its Affiliates globally in connection with providing the Services (the "Approved Purpose").  You warrant and undertake to comply with all Applicable Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You has done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

C.   Hong Kong

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Hong Kong Personal Data (Privacy) Ordinance (Cap. 486), as amended from time to time; and the term "personal data" has the meaning designated by the Hong Kong Personal Data (Privacy) Ordinance (Cap. 486).

  b. You agree that First Advantage is a data processor (which shall have the meaning designated by the Hong Kong Personal Data (Privacy) Ordinance (Cap. 486)) and will process personal data about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agrees that personal data may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal data may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractors has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause. First Advantage will take all reasonable steps and maintain appropriate technical and organizational security controls to protect personal data against unauthorised or accidental access, processing, erasure, loss or misuse. In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal data equivalent to the Applicable Privacy Laws. First Advantage agrees not to store the personal data for a period longer than required for the Approved Purpose. Upon expiration or termination of this Agreement, First Advantage will return to You all personal data received from You in connection with the Services and shall refrain from any further processing and use of such data.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agrees that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal data obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

D.   Japan

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Act on the Protection of Personal Information, as amended from time to time; and the term "personal information" has the meaning designated by the Act on the Protection of Personal Information.

  b. You agree that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

E.   Malaysia

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Personal Data Protection Act (PDPA) 2010, its regulations, codes of practices, guidelines and statutory orders, as amended from time to time; and the term "personal information" has the meaning of "personal data" designated and defined by the Personal Data Protection Act (PDPA) 2010.

  b. You agrees that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take practical steps to keep the data secure.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

F.   New Zealand 

  a. You shall comply with the requirements of any New Zealand laws, regulations and standards applicable to the Services and to its industry ("Applicable Law"), including with the requirements of the Privacy Act of 1993, as amended from time to time, to the extent that You collects and provides to First Advantage, or First Advantage otherwise obtains in connection with providing the Services, any personal information about the relevant job applicant or other individuals (“Personal Information”).

  b. You agree that First Advantage will process Personal Information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You shall obtain a relevant individual’s written consent that meets the Applicable Laws prior to ordering Services from First Advantage.  You acknowledge that a relevant individual may also be asked to sign consent forms required by government agencies or other sources to enable these sources to disclose information to First Advantage. You further agree that First Advantage reserves the right not to commence any work in respect of Your request until First Advantage has received all the necessary signed consents required from the relevant individual who is the subject of the request.

  c. For the purposes of this User Agreement, You act as the collector and holder of the Personal Information of the job applicants and First Advantage as your third party agent. Accordingly, You will continue to be responsible for ensuring the requirements of the Privacy Act 1993 are complied with in respect of all Personal Information collected by You and disclosed to First Advantage. First Advantage shall nevertheless implement and maintain technical and organizational security measures in accordance with the security principles applicable to the Services. You acknowledge and accept that First Advantage will use the services of other affiliated and unaffiliated third parties (the "Subcontractors") to provide limited services on its behalf, such as providing hosting services for the servers used to provide the Services or research and report services.  These Subcontractors may be located in the United States, India, and other jurisdictions. Any Subcontractors to whom First Advantage transfers Personal Information will have entered into written agreements with First Advantage requiring that the Subcontractor abide by privacy terms no less protective than this Agreement.

G.   Philippines 

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to Republic Act No. 10173 or the Philippine Data Privacy Act of 2012 and State and Territory privacy laws, as amended from time to time; and the terms "personal information" and “sensitive personal information” have the meaning designated by the Philippine Data Privacy Act of 2012.

  b. You agree that First Advantage will process personal information about job applicants and other individuals for You according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause and of the Applicable Privacy Laws.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures with a comparable level of protection as provided under the Applicable Privacy Laws and to take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) obtaining and receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

H.   Singapore  

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Personal Data Protection Act 2012, as amended from time to time; and the term "personal data" has the meaning designated by the Personal Data Protection Act 2012.

  b. You agree that First Advantage is a Data Intermediary (as defined under the Applicable Privacy Laws) and will process personal data about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under your sole instructions  and for the sole purpose of pre-employment and employment screening.  First Advantage shall comply with its obligations under the Applicable Privacy Laws, which are to: (i) make reasonable security arrangements to protect personal data in its possession or under its control in order to prevent unauthorised access, collection, use, disclosure, copying, modification, disposal or similar risks; and (ii) cease to retain documents containing personal data, or remove the means by which the personal data can be associated with particular individuals, as soon as it is reasonable to assume that the purpose for which that personal data was collected is no longer being served by retention of the personal data, and the retention is no longer necessary for legal or business purposes. You acknowledge and agree that personal data may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal data may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal data for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agrees that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal data obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

I.   South Korea 

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Personal Information Protection Act (“PIPA”) as amended from time to time; and the term "personal information" has the meaning designated by PIPA.

  b. You agree that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under your sole instructions and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

  e. First Advantage shall implement the technical and managerial safeguards necessary to ensure the security of the personal data as required under the PIPA. 

  f. You may request that: (i) First Advantage inspect the conditions of maintenance of the personal data that You provided to First Advantage; and (ii) First Advantage report to You on the results of the inspection.  You may also directly request the inspection of the maintenance status and the correction of any issues if it determines that doing so is necessary.  

  g. First Advantage shall be liable for any damages incurred by You, the data subject, or a third party stemming from a violation of this User Agreement by First Advantage, First Advantage’s employee or officer, or other outsourced provider hired by First Advantage in the course of processing the outsourced or re-outsourced personal data.  
`,
    tc_aus:
`Countries Covered: 

Australia
China
Hong Kong
Japan
Malaysia
New Zealand
Philippines
Singapore
South Korea

Terms to be incorporated for all regions:  

1. SCOPE OF SERVICES.  First Advantage Limited (“First Advantage”) agrees to provide, pre-employment and employment screening services to Customer/Client (“You”) as detailed in accordance with the terms and conditions herein. By clicking the "ACCEPT" Button, You are consenting to be bound by this User Agreement.

2. Fees and Payment.  All amounts due by You, inclusive of service charges and applicable taxes, hereunder shall be paid in the currency selected via credit card or wire transfer to an account designated by First Advantage. The amounts due by You when settled are non-refundable. Wallet credits will be provided, which will be available for usage for succeeding transactions. Order cancellations post payments will be subject to wallet credits.  
First Advantage has an automated order assessment methodology that supports intelligent comparison of check orders paid versus actual checks required to be conducted based on candidate declared details. This methodology determines final amounts to be charged to You. As additional checks are detected, request for secondary payment will be secured from You to complete the transaction.

3. DISCLAIMER OF WARRANTIES.  To the extent permitted by law and except as otherwise expressly provided, First Advantage and its Affiliates make no and disclaim all warranties and representations with respect to the Services provided pursuant to this User Agreement, whether such warranties and representations are express or implied in fact or by operation of law (other than those in the Competition and Consumer Act 2010 (Cth) which cannot be lawfully excluded), contained in or derived from this User Agreement, any other documents referenced in this User Agreement, or any other materials or communications whether oral or written, including without limitation, implied warranties of merchantability and fitness for a particular purpose and implied warranties arising from the course of dealing or a course of performance with respect to the accuracy, validity, or completeness of any Service.  To the extent permitted by law (including the Competition and Consumer act 2010 (Cth)), First Advantage's liability will be limited, at First Advantage's option, to any one or more of the following, in accordance with section 64a of the Australian Consumer Law: (i) the supplying of the services again; or (ii) the payment of the cost of having the services supplied again.

4. Applicable Privacy Laws.  You will comply with all "Applicable Privacy Laws", made available online at <br> <a style="color:blue !important;cursor:pointer" href="#legals" >“Legal Compliance”</a>. Any changes when any made to this section, will be posted at the above link. It is your responsibility to ensure that you understand and comply with all Applicable Privacy Laws, so you should periodically check this section for any changes.

5. INDEMNIFICATION.  You shall indemnify, defend and hold harmless First Advantage from and against any claim, suit, proceeding, damages, costs, expenses (including, without limitation, reasonable attorneys’ fees and court costs) brought by a third party against or suffered First Advantage arising from your violation of law, negligence or failure to comply with the terms and conditions of this User Agreement.

6. LIMITATION OF LIABILITY. First Advantage shall not be liable for any indirect, incidental, contingent, consequential, punitive, exemplary, special or similar damages, including but not limited to, loss of profits or loss of data, whether incurred as a result of negligence or otherwise.  First Advantage’s aggregate liability damages arising out of or in connection with this User Agreement, including as a result of any negligence on the part of First Advantage, shall not exceed three times the amount paid by You to First Advantage for the particular service giving rise to such damages. The limitations of the liability pursuant to this section applies only to the extent permitted by law.

7. Your Obligations.  You agree, and must ensure any organisation to which You provide any information provided to You by First Advantage agree that:

  a. You will only use the reports and information First Advantage provides for the purposes of pre-employment and employment screening or otherwise in accordance with the consent given to You by the relevant individual;

  b. You will take proper and reasonable steps to keep the information First Advantage supplies to You confidential and secure, and will not disclose it without the relevant individual’s consent except as otherwise permitted or required by law;

  c. First Advantage may modify the scope of Service at any time upon reasonable notice to You unless prior notice cannot be provided due to First Advantage’s obligations to comply with law, regulation and/or data provider requirements.  Notwithstanding anything to the contrary in this User Agreement, if First Advantage modifies the scope of the Service, You agree to comply with all such additional requirements and any additional fees or costs for such compliance which may be passed through to You.

  d. You warrant that the fax, email or mailing address You provide to First Advantage for correspondence is suitable for maintaining the confidentiality of the information First Advantage sends to You and You will notify First Advantage promptly if any need arises for You to change it; and

  e. First Advantage does not transfer any right, title or interest in any intellectual property rights in its business processes or in the Service that it is providing to You under this User Agreement.

8. Confidentiality.  The term “Confidential Information” means this User Agreement and all data, trade secrets, business and personal information and other information of any kind whatsoever that First Advantage discloses to You. You must not disclose Confidential Information provided by First Advantage to any third party other than on a “need to know” basis and then only to: (i) Your employees subject to a written confidentiality agreement and (iii) as required by law or as otherwise expressly permitted by this User Agreement.  You must not use or disclose Confidential Information of Discloser for any purpose other than to carry out this User Agreement. The obligations of confidentiality in this Section shall not apply to any information that: (i) You rightfully have in your possession when disclosed to it, free of obligation to First Advantage to maintain its confidentiality; (ii) You independently develop without access to First Advantage’s Confidential Information; (iii) is or becomes known to the public other than by breach of this Section by You; or (iv) is rightfully received by You from a third party without the obligation of confidentiality.

9. Termination: First Advantage will immediately terminate your right to receive any Service under this User Agreement if You fail to comply with the terms and conditions of this User Agreement, or You fail to comply with any law applicable to the Service provided to You pursuant to this User Agreement.

10. Miscellaneous: This User Agreement, constitute the final and entire agreement between the parties with respect to the Service. There are no representations, warranties, or agreements among the parties with respect to the Services contained herein, which are not fully expressed in this Agreement.  This User Agreement is governed by the laws of the Country where the Service is being provided and each party submits to the exclusive jurisdiction in and of the courts of  such countries and the courts which may hear appeals from those. If any provision of this Agreement is held to be invalid or unenforceable, the remaining provisions shall be unaffected. A waiver by either party of any term or condition of this User Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. First Advantage may assign its rights under this User Agreement without condition. This User Agreement will be binding upon and inure to the benefit of the parties, their successors and permitted assigns. A listing of First Advantage’s Affiliates is set forth at: <a href="https://www.fadv.com/Portals/0/Downloads/legal/First_Advantage-Affiliate_Listing_10142016.pdf" target="_blank" >https://www.fadv.com/Portals/0/Downloads/legal/First_Advantage-Affiliate_Listing_10142016.pdf</a> .

<b id="legals">“Legal Compliance”</b>

A.   Australia

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Privacy Act 1988 (Cth), the Australian Privacy Principles, and State and Territory privacy laws, as amended from time to time; and the term "personal information" has the meaning designated by the Privacy Act 1988 (Cth).

  b. You agree that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledges and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertakes to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You has done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

B.   China

  In this User Agreement, “Applicable Laws” shall refer to country laws, directives, rules, regulations, executive orders, regulatory guidance, regulatory requirements and any form of secondary legislation, resolution, policy guideline, concession or case law from time to time that apply to either party and its affiliates or the services, including (i) data protection, privacy or similar laws and regulations anywhere in the world applicable to persons in possession of personal data or to the processing of personal data, and (ii) employment laws.  You agree that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its Affiliates globally in connection with providing the Services (the "Approved Purpose").  You warrant and undertake to comply with all Applicable Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You has done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

C.   Hong Kong

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Hong Kong Personal Data (Privacy) Ordinance (Cap. 486), as amended from time to time; and the term "personal data" has the meaning designated by the Hong Kong Personal Data (Privacy) Ordinance (Cap. 486).

  b. You agree that First Advantage is a data processor (which shall have the meaning designated by the Hong Kong Personal Data (Privacy) Ordinance (Cap. 486)) and will process personal data about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agrees that personal data may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal data may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractors has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause. First Advantage will take all reasonable steps and maintain appropriate technical and organizational security controls to protect personal data against unauthorised or accidental access, processing, erasure, loss or misuse. In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal data equivalent to the Applicable Privacy Laws. First Advantage agrees not to store the personal data for a period longer than required for the Approved Purpose. Upon expiration or termination of this Agreement, First Advantage will return to You all personal data received from You in connection with the Services and shall refrain from any further processing and use of such data.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agrees that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal data obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

D.   Japan

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Act on the Protection of Personal Information, as amended from time to time; and the term "personal information" has the meaning designated by the Act on the Protection of Personal Information.

  b. You agree that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

E.   Malaysia

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Personal Data Protection Act (PDPA) 2010, its regulations, codes of practices, guidelines and statutory orders, as amended from time to time; and the term "personal information" has the meaning of "personal data" designated and defined by the Personal Data Protection Act (PDPA) 2010.

  b. You agrees that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take practical steps to keep the data secure.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

F.   New Zealand 

  a. You shall comply with the requirements of any New Zealand laws, regulations and standards applicable to the Services and to its industry ("Applicable Law"), including with the requirements of the Privacy Act of 1993, as amended from time to time, to the extent that You collects and provides to First Advantage, or First Advantage otherwise obtains in connection with providing the Services, any personal information about the relevant job applicant or other individuals (“Personal Information”).

  b. You agree that First Advantage will process Personal Information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You shall obtain a relevant individual’s written consent that meets the Applicable Laws prior to ordering Services from First Advantage.  You acknowledge that a relevant individual may also be asked to sign consent forms required by government agencies or other sources to enable these sources to disclose information to First Advantage. You further agree that First Advantage reserves the right not to commence any work in respect of Your request until First Advantage has received all the necessary signed consents required from the relevant individual who is the subject of the request.

  c. For the purposes of this User Agreement, You act as the collector and holder of the Personal Information of the job applicants and First Advantage as your third party agent. Accordingly, You will continue to be responsible for ensuring the requirements of the Privacy Act 1993 are complied with in respect of all Personal Information collected by You and disclosed to First Advantage. First Advantage shall nevertheless implement and maintain technical and organizational security measures in accordance with the security principles applicable to the Services. You acknowledge and accept that First Advantage will use the services of other affiliated and unaffiliated third parties (the "Subcontractors") to provide limited services on its behalf, such as providing hosting services for the servers used to provide the Services or research and report services.  These Subcontractors may be located in the United States, India, and other jurisdictions. Any Subcontractors to whom First Advantage transfers Personal Information will have entered into written agreements with First Advantage requiring that the Subcontractor abide by privacy terms no less protective than this Agreement.

G.   Philippines 

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to Republic Act No. 10173 or the Philippine Data Privacy Act of 2012 and State and Territory privacy laws, as amended from time to time; and the terms "personal information" and “sensitive personal information” have the meaning designated by the Philippine Data Privacy Act of 2012.

  b. You agree that First Advantage will process personal information about job applicants and other individuals for You according to the criteria established by You, and provide reports to You, all under the sole instructions of You and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause and of the Applicable Privacy Laws.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures with a comparable level of protection as provided under the Applicable Privacy Laws and to take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) obtaining and receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

H.   Singapore  

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Personal Data Protection Act 2012, as amended from time to time; and the term "personal data" has the meaning designated by the Personal Data Protection Act 2012.

  b. You agree that First Advantage is a Data Intermediary (as defined under the Applicable Privacy Laws) and will process personal data about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under your sole instructions  and for the sole purpose of pre-employment and employment screening.  First Advantage shall comply with its obligations under the Applicable Privacy Laws, which are to: (i) make reasonable security arrangements to protect personal data in its possession or under its control in order to prevent unauthorised access, collection, use, disclosure, copying, modification, disposal or similar risks; and (ii) cease to retain documents containing personal data, or remove the means by which the personal data can be associated with particular individuals, as soon as it is reasonable to assume that the purpose for which that personal data was collected is no longer being served by retention of the personal data, and the retention is no longer necessary for legal or business purposes. You acknowledge and agree that personal data may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal data may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal data for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agrees that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal data obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

I.   South Korea 

  a. In this User Agreement, "Applicable Privacy Laws" include but are not limited to the Personal Information Protection Act (“PIPA”) as amended from time to time; and the term "personal information" has the meaning designated by PIPA.

  b. You agree that First Advantage will process personal information about job applicants and other individuals according to the criteria established by You, and provide reports to You, all under your sole instructions and for the sole purpose of pre-employment and employment screening.  You acknowledge and agree that personal information may be used or processed by First Advantage and its affiliates globally in connection with providing the Services (the "Approved Purpose").  You acknowledge and agree that personal information may be used or processed by third party contractors on behalf of First Advantage for the Approved Purpose, provided that any such third party contractor has entered into a written agreement with First Advantage requiring the third party contractor to comply with privacy terms no less protective than the provisions of this clause.  In the case of disclosures to overseas entities, First Advantage will instruct the recipient entity to apply data protection policies and procedures and take reasonable steps to keep the data secure, although the importing countries may not provide statutory protections for personal information equivalent to the Applicable Privacy Laws.

  c. You warrant and undertake to comply with all Applicable Privacy Laws in performing its obligations under this Agreement and in connection with First Advantage providing the Services, including obtaining all necessary consents and giving all notices required pursuant to the Applicable Privacy Laws in order to permit First Advantage to use and disclose personal information for the Approved Purpose.  You must keep adequate documents and records in sufficient detail to evidence Your compliance with this clause.  You further agree that First Advantage reserves the right not to commence any work in respect of Your request until You have done everything necessary to comply with the Applicable Privacy Laws, including (without limitation) receiving all the necessary signed consents required from the relevant individual who is the subject of the request.  You must immediately notify First Advantage if the relevant individual withdraws any necessary consents.

  d. You must cooperate reasonably with First Advantage in relation to any investigation or enforcement action by a regulatory authority in connection with personal information obtained, used or processed in connection with this Agreement, including (without limitation) providing all information and assistance reasonably requested by First Advantage.  You must consult with First Advantage and allow First Advantage the right to make representations in connection with any investigation or enforcement action before You respond to that investigation or action.

  e. First Advantage shall implement the technical and managerial safeguards necessary to ensure the security of the personal data as required under the PIPA. 

  f. You may request that: (i) First Advantage inspect the conditions of maintenance of the personal data that You provided to First Advantage; and (ii) First Advantage report to You on the results of the inspection.  You may also directly request the inspection of the maintenance status and the correction of any issues if it determines that doing so is necessary.  

  g. First Advantage shall be liable for any damages incurred by You, the data subject, or a third party stemming from a violation of this User Agreement by First Advantage, First Advantage’s employee or officer, or other outsourced provider hired by First Advantage in the course of processing the outsourced or re-outsourced personal data.  
`,
}
export default data;
